In [2]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [3]:
#Définir les entrées 
x = torch.rand(1,3)
print(x)

tensor([[0.1545, 0.3078, 0.3657]])


In [4]:
#Définir le module de la couche 
lin = torch.nn.Linear(3,2)

In [5]:
#Visualiser les paramètres qui ont été définis par défaut 
for param in lin.parameters():
    print(param) #w pour le 1e, biais pour le 2e

Parameter containing:
tensor([[-0.4111, -0.5456, -0.5027],
        [ 0.3959,  0.4189, -0.5005]], requires_grad=True)
Parameter containing:
tensor([0.1731, 0.1723], requires_grad=True)


In [6]:
#Définir la sortie de la couche 
y = lin(x) 
print(y)

tensor([[-0.2422,  0.1794]], grad_fn=<AddmmBackward0>)


In [15]:
#Vérification que y = x@w + biais 
#Pour trois entrées, 1 sortie : (x1*wy1,1+...+x3*wy1,3)+biais = y1 
(0.1545*-0.4111+0.3078*-0.5456+0.3657* -0.5027)+0.1731

-0.24218801999999998